### ISSUE TITLE
The latest release v1.6.1 is causing error while executing BOM

### ISSUE THREAD

**Issue by dimallya** [cloud-native-toolkit/terraform-tools-argocd-bootstrap#12]
While trying to deploy software BoMs (CP4S, Turbo etc) the latest release of this module is causing following error:
<img width="1146" alt="image" src="https://user-images.githubusercontent.com/99815425/160060838-c836c730-f83c-416d-b02d-ed6add33b9c8.png">
However, while changing version back to v1.6.0 we are able to deploy everything successfully.

**Comment by triceam** [comment]
I've not seen this one before... were you executing inside of the cli-tools container, or from a local shell?  I wonder if this is the result of a back-level cli version .

**Comment by dimallya** [comment]
@triceam We were trying to execute from local shell. Could you please let us know which CLI version has be to upgraded to overcome this issue. TIA.

**Comment by triceam** [comment]
Try executing inside of the cli-tools image, which should have all of the CLIs that you need.

From a command line/terminal, `cd` into the directory containing your terraform code, and run this command to open an interactive shell inside of the cli-tools image:
```
docker run -it \
  -v ${PWD}:/terraform \
  -w /terraform \
  quay.io/ibmgaragecloud/cli-tools:v1.1
  ```

**Comment by dimallya** [comment]
@triceam @seansund 
I tried using cli-tools image and getting the same error!
![image](https://user-images.githubusercontent.com/99815425/160380686-fac3771d-2f25-4cc0-8334-1b3ebbf46aae.png)

**Comment by seansund** [comment]
v1.6.2 has been released. Can you see if that fixed things?

**Comment by dimallya** [comment]
@seansund v1.6.2 also has same issue.
