### ISSUE TITLE
Argocd Service Account permission issue

### ISSUE THREAD

**Issue by RamyaRaghuveera** [cloud-native-toolkit/terraform-tools-argocd-bootstrap#22]
Application in Argocd fails as the Argocd Service account is not able to create particular resources in given namespace. Attaching the screenshot for reference
<img width="1371" alt="ArgocdSApermissionissue" src="https://user-images.githubusercontent.com/16119907/163240808-6e063c6e-86da-410c-b17c-3a3531839259.png">

**Comment by seansund** [comment]
What clusterrole and role resources have been created in the cluster? There should be a cluster role that gives argocd permission across the entire cluster and a role in the namespace
